
$(document).ready(function() {
    var randomQuotes;
    var randomNum;
    getQuote();
    function getQuote() {
        var quotes = ["There are five billion people living on this planet. But you fall in love with one particular person, and you won't swap her for any other.",
        "People generally see what they look for and hear what they listen for.",
        "You don't get to choose if you get hurt in this world...but you do have some say in who hurts you.",
        "The world is not a wish-granting factory.",
        "Destroying things is much easier than making them.",
        "To be successful you need friends and to be very successful you need enemies.",
        "Life is like a novel. It's filled with suspense. You have no idea what is going to happen until you turn the page.",
        "It's much better to do good in a way that no one knows anything about it.",
        "There comes a time when you have to choose between turning the page and closing the book.",
        "There are perhaps no days of our childhood we lived so fully as those we spent with a favorite book.",
        "A book is the only place in which you can examine a fragile thought without breaking it.",
        "If one cannot enjoy reading a book over and over again, there is no use in reading it at all.",
        "Read the best books first, or you may not have a chance to read them at all.",
        "We do not remember days, we remember moments.",
        "Life's most persistent and urgent question is, 'What are you doing for others?'",
        "Life is really simple, but we insist on making it complicated.",
        "Beware the barrenness of a busy life.",
        "You have enemies? Good. That means you've stood up for something, sometime in your life.",
        "Growth is the only evidence of life.",
        "Sometimes the questions are complicated and the answers are simple.",
        "Things change. And friends leave. Life doesn't stop for anybody.",
        "The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.",
        "All our dreams can come true if we have the courage to pursue them.",
        "In the end, it's not the years in your life that count. It's the life in your years.",
        "We do not remember days, we remember moments.",
        "Life's most persistent and urgent question is, 'What are you doing for others?'",
        "Life is really simple, but we insist on making it complicated.",
        "Beware the barrenness of a busy life.",
        "You have enemies? Good. That means you've stood up for something, sometime in your life.",
        "Growth is the only evidence of life.",
        "Sometimes the questions are complicated and the answers are simple.",
        "Don’t smother each other. No one can grow in the shade.",
        "The royal road to a man’s heart is to talk to him about the things he treasures most.",
        "When dealing with people, remember you are not dealing with creatures of logic, but creatures of emotion.",
        "May the Force be with you.",
        "There’s no place like home.",
        "The first rule of Fight Club is you do not talk about Fight Club.",
        "Keep your friends close, but your enemies closer.",
        "They may take our lives, but they'll never take our freedom!",
        "The greatest trick the devil ever pulled was convincing the world he didn't exist.",
        "I'm gonna make him an offer he can't refuse.",
        "It’s a fool looks for logic in the chambers of the human heart.",
        "The best motivation always comes from within.",
        "The more I practice, the luckier I get.",
        "One man practicing sportsmanship is far better than 50 preaching it.",
        "Winning is not everything – but making the effort to win is.",
        "A good coach will make his players see what they can be rather than what they are.",
        "You miss 100 percent of the shots you don’t take",
        "Gold medals aren't really made of gold. They're made of sweat, determination and a hard-to-find alloy called guts",
        "Everybody has a plan until they get punched in the face",
        "Most talented players don’t always succeed. Some don’t even make the team. It’s more what’s inside.",
        "If you can’t outplay them, outwork them.",
        "You can't put a limit on anything. The more you dream, the farther you get.",
        "It is not the size of a man but the size of his heart that matters.",
        "You have to believe in yourself when no one else does - that makes you a winner right there.",
        "I skate to where the puck is going to be, not where it has been.",
        "One man can be a crucial ingredient on a team, but one man cannot make a team.",
        "The more difficult the victory, the greater the happiness in winning.",
        "Experience is a hard teacher because she gives the test first, the lesson afterward.",
        "Today I will do what others won’t, so tomorrow I can accomplish what others can’t.",
        "I think it’s the mark of a great player to be confident in tough situations.",
        "You’re never a loser until you quit trying.",
        "Sometimes the biggest problem is in your head. You’ve got to believe.",];
        var author =["Jostein Gaarder, The Solitaire Mystery",
        "Harper Lee, To Kill a Mockingbird",
        "John Green, The Fault In Our Stars",
        "John Green, The Fault In Our Stars",
        "Suzanne Collins, The Hunger Games",
        "Sidney Sheldon, The Other Side of Midnight",
        "Sidney Sheldon",
        "Leo Tolstoy Anna Karenina",
        "Josh Jameson",
        "Marcel Proust",
        "Edward P. Morgan",
        "Oscar Wilde",
        "Henry David Thoreau",
        "Cesare Pavese",
        "Martin Luther King Jr.",
        "Confucius",
        "Socrates",
        "Winston Churchill",
        "John Henry Newman",
        "Dr. Seuss",
        "Stephen Chbosky",
        "Mark Twain",
        "Walt Disney",
        "Abraham Lincoln",
        "Cesare Pavese",
        "Martin Luther King, Jr.",
        "Confucius",
        "Socrates",
        "Winston Churchill",
        "John Henry Newman",
        "Dr. Seuss",
        "Leo Buscaglia",
        "Dale Carnegie",
        "Dale Carnegie",
        "Star Wars 1977",
        "The Wizard of Oz 1939",
        "Fight Club 1999",
        "The Godfather Part II 1974",
        "Braveheart 1995",
        "The Usual Suspects 1995",
        "The Godfather 1972",
        "Where Art Thou? 2000",
        "Michael Johnson",
        "Gary Player",
        "Knute Rockne",
        "Vince Lombardi",
        "Ara Paraeghian",
        "Wayne Gretzky",
        "Dan Gable",
        "Mike Tyson",
        "Brett Favre",
        "Ben Hogan",
        "Michael Phelps",
        "Evander Holyfield",
        "Venus Williams",
        "Wayne Gretzy Hockey Star",
        "Kareem Abdul-Jabbar",
        "Pele",
        "Vernon Law",
        "Jerry Rice",
        "John McEnroe",
        "Mike Dikta",
        "Jack Nicklaus",];
        randomNum = Math.floor(Math.random()*quotes.length);
                    randomQuotes = quotes[randomNum];
                    author = author[randomNum];
                    $(".quote").text(randomQuotes);
                    $(".author").text(author);
    }
        $("#tweet").on("click",function() {
            window.open("https://twitter.com/intent/tweet?text="+randomQuotes + " " + author );
        });

        $("#newQuote").on("click", function() {
            getQuote();
        });
});